AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template '
Parameters:
  Env: 
    Type: String
  DBPassword:
    Default: root1234
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '6144'
    ConstraintDescription: must be between 5+

Resources:
  bpDataBase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: 'bpDatabase'
      DBUsername: '{{resolve:ssm:/bpartners/${Env}/dbusername}}'
      AllocatedStorage:
        Ref: DBAllocatedStorage
      Engine: postgres
      MasterUserPassword:
        Ref: DBPassword

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDataBase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDataBase
          - Endpoint.Port
        - "/"
        - DBName