AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template '
Parameters:
  DBPassword:
    Default: root1234
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '6144'
    ConstraintDescription: must be between 5+

Resources:
  bpDataBase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: 'bpDatabase'
      AllocatedStorage:
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBClass
      Engine: postgres
      MasterUsername: '{{resolve:ssm:/bpartners/dev/dbuser}}'
      MasterUserPassword:
        Ref: DBPassword

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDataBase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDataBase
          - Endpoint.Port
        - "/"
        - Ref: DBName