AWSTemplateFormatVersion: '2010-09-09'
Description: 'B-partners database'
Parameters:
  Env: 
    Type: String
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.

Resources:
  bpDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Join ["",  [!Ref Env , BpartnersDb ]]
      AllocatedStorage: '5'
      DBInstanceClass:
        Ref: DBClass
      Engine: postgres
      MasterUsername: !Sub '{{resolve:ssm:/bpartners/${Env}/dbusername}}'
      MasterUserPassword: !Sub '{{resolve:ssm:/bpartners/${Env}/db/password}}'

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    # Value : '{{resolve:ssm:/bpartners/dev/url}}'
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Port
        - "/"database
        - DBName