AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template'
Parameters:
  Env: 
    Type: String
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '6144'
    ConstraintDescription: must be between 5+

Resources:
  bpDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Join ["",  [!Ref Env , -bpartners-db ]]
      AllocatedStorage: 
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBClass
      Engine: postgres
      MasterUsername: 'blabla'
      MasterUserPassword: 'blabla'

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Port
        - "/"
        - DBName