AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template '
Parameters:
  Env: 
    Type: String
  DBUsername:
    Default: root
    NoEcho: 'false'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.

Resources:
  bpDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Join ['' , !Ref Env , bparterns-db]
      AllocatedStorage: 5
      Engine: postgres
      MasterUsername: '{{resolve:ssm:/bpartners/${Env}/dbuser:1}}'
      MasterUserPassword: '{{resolve:ssm:/bpartners/${Env}/db/password:1}}'

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Port
        - "/"
        - DBName