AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template '
Parameters:
  DBName:
    Default: bpDatabase
    Type: String
    MinLength: '5'
    MaxLength: '15'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUsername:
    Default: !Sub '{{resolve:ssm:/bpartners/env/dbusername}}'
    NoEcho: 'false'
    Type: AWS::SSM::Parameter::Value<String>
    MinLength: '5'
    MaxLength: '15'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    Default: root1234
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '6144'
    ConstraintDescription: must be between 5+

Resources:
  bpDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName:
        Ref: DBName
      AllocatedStorage:
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBClass
      Engine: postgres
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Port
        - "/"
        - Ref: DBName