AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template'
Parameters:     
  DBUsername:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '{{resolve:ssm:/bpartners/${Env}/dbusername}}'
    NoEcho: 'false'
    MinLength: '5'
    MaxLength: '15'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Type: String
    MinLength: '8'
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    
    MaxValue: '6144'
    ConstraintDescription: must be between 5+

Resources:
  pgDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName:
        Default: ${Env}-bpartners-db
        Type: String
        MinLength: '5'
        MaxLength: '15'
        AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
        ConstraintDescription: must begin with a letter and contain only alphanumeric
          characters. 
      AllocatedStorage:
        Ref: DBAllocatedStorage
      Engine: postgres
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - pgDB
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - pgDB
          - Endpoint.Port
        - "/"
        - DBName