AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template '
Parameters:
  Env: 
    Type: String
    Default: dev

Resources:
  bpDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Join ['' , !Ref Env , bpartners-db]
      AllocatedStorage: 5
      Engine: postgres
      MasterUsername: '{{resolve:ssm:/bpartners/${Env}/dbusername:1}}'
      MasterUserPassword: '{{resolve:ssm:/bpartners/${Env}/db/password:1}}'

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Port
        - "/"
        - DBName