AWSTemplateFormatVersion: '2010-09-09'
Description: 'PostgreSQL RDS Template '
Parameters:
  DBUsername:
    Default: root
    NoEcho: 'false'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '6144'
    ConstraintDescription: must be between 5+

Resources:
  bpDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: db
      AllocatedStorage:
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBClass
      Engine: postgres
      MasterUsername: '{{resolve:ssm:/bpartners/dev/dbuser}}'

Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:postgresql://
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - bpDatabase
          - Endpoint.Port
        - "/"
        - DBName