AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket template'

Resources:
 S3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: bucket

Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket