AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Env: 
    Type: String 

Resources: 
  SourceQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join ['' , [!Ref Env , -bpartners-api]]
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "DeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5
  DeadLetterQueue:
    Type: AWS::SQS::Queue
