AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Env: 
    Type: String
  SourceQueue: 
    Type: String 
    Default: !Join ['',  [!Ref Env , bpartners-api]]
  DeadLetterQueue: 
    Type: String 
    Default: !Join ['',  [!Ref Env , bpartners-api-dl]]
Resources: 
  MySourceQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Ref SourceQueue
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "MyDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5
  MyDeadLetterQueue: 
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref DeadLetterQueue
Outputs: 
  SourceQueueURL: 
    Description: "URL of source queue"
    Value: 
      Ref: !Ref SourceQueue
  SourceQueueARN: 
    Description: "ARN of source queue"
    Value: 
      Fn::GetAtt: 
        - !Ref SourceQueue
        - "Arn"
  DeadLetterQueueURL: 
    Description: "URL of dead-letter queue"
    Value: 
      Ref: !Ref DeadLetterQueue
  DeadLetterQueueARN:
    Description: "ARN of dead-letter queue"
    Value:
      Fn::GetAtt:
        - !Ref DeadLetterQueue
        - "Arn"