AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Env: 
    Type: String 

Resources: 
  MailboxQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join ['' , [!Ref Env , -bpartners]]
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "DeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5
  
  MailboxSSM: 
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['', [/bpartners/, !Ref Env, /sqs/mailbox-queue-url]]
      Type: String
      Value: !Ref MailboxQueue.QueueURL

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    QueueName: !Join ['' , [!Ref Env , -bpartners-dl]]
  
  # DeadLetterQueue:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name: !Join ['', [/bpartners/, !Ref Env, /sqs/deadletter-queue-url]]
  #     Type: String
  #     Value: !Ref DeadLetterQueue.QueueURL

Outputs: 
  MailboxQueueURL: 
    Value: 
      Ref: "MailboxQueue"

  DeadLetterQueueURL: 
    Value: 
      Ref: "DeadLetterQueue"