AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Env: 
    Type: String
Resources: 
  MySourceQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join ['' , !Ref Env , -bparnters-api]
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "MyDeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5
  MyDeadLetterQueue: 
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ['' , !Ref Env , -bpartners-api-dl]
Outputs: 
  SourceQueueURL: 
    Description: "URL of source queue"
    Value: 
      Ref:  !Join ['' , !Ref Env , -bparnters-api]
  SourceQueueARN: 
    Description: "ARN of source queue"
    Value: 
      Fn::GetAtt: 
        -  !Join ['' , !Ref Env , -bparnters-api]
        - "Arn"
  DeadLetterQueueURL: 
    Description: "URL of dead-letter queue"
    Value: 
      Ref:  !Join ['' , !Ref Env , -bpartners-api-dl]
  DeadLetterQueueARN:
    Description: "ARN of dead-letter queue"
    Value:
      Fn::GetAtt:
        -  !Join ['' , !Ref Env , -bpartners-api-dl]
        - "Arn"