AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Env: 
    Type: String 

Resources: 
  MailboxQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join ['' , [!Ref Env , -bpartners]]
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "DeadLetterQueue"
            - "Arn"
        maxReceiveCount: 5
  DeadLetterQueue:
    Type: AWS::SQS::Queue


Outputs: 
  MailboxQueueURL: 
    Value: 
      Ref: "MailboxQueue"
  DeadLetterQueueURL: 
    Value: 
      Ref: "DeadLetterQueue"
  DeadLetterQueueARN: 
    Value: 
      Fn::GetAtt: 
        - "DeadLetterQueue"
        - "Arn"