AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Env: 
    Type: String 

Resources: 
  MailboxQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join ['' , [!Ref Env , -bpartners]]
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5
  DeadLetterQueue:
    Type: AWS::SQS::Queue

  MailboxQueueSSM: 
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/bpartners/ , !Ref Env , /sqs/mailbox-queue-url]]
      Value: !Ref MailboxQueue
  
  DeadLetterQueueSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/bpartners/ , !Ref Env , /sqs/dead-letter-queue-url]]
      Value: !Ref DeadLetterQueue

  EventBridgeBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Join ['', [!Ref Env, -bpartners]]

  EventBridgeArchive:
    Type: AWS::Events::Archive
    Properties:
      ArchiveName: !Join ['', [!Ref Env, -bpartners, -archive]]
      SourceArn: !GetAtt EventBridgeBus.Arn
      
  EventBridgeRule:
    Type: AWS::Event::Rule
    Properties:
      Name: !Join ['', [!Ref Env, -bpartners, -from-api-to-api]]
      EventBusName: !GetAtt EventBridgeBus.Name
      EventPattern:
        Source:
          - aws.ecs

Outputs: 
  MailboxQueueURL: 
    Value: !Ref MailboxQueueSSM
  DeadLetterQueueURL: 
    Value: !Ref DeadLetterQueueSSM